name: Deploy to Build Branch

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Build and deploy
        run: |
          mkdir dist
          cd dist

          git init

          git config user.name "gualter"
          git config user.email "gualter@gualter.com"
          

          git remote add origin https://github.com/Matyrela/Space-apps-orrery-web-app.git
          git fetch origin build || echo "No build branch yet"

          git checkout -b build || git checkout build

          cd ..

          npm install
          npm run build

          cd dist

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add *
          
          git commit -m "Deploy to build branch" || echo "No changes to commit"
          git push --force origin build
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
