name: Deploy to Build Branch

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      -   uses: actions/checkout@v1
      -   name: Setup SSH Keys and known_hosts
          env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
              mkdir -p ~/.ssh
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              ssh-agent -a $SSH_AUTH_SOCK > /dev/null
              ssh-add - <<< "${{ secrets.VERSION_BUMPER_SECRET }}"

      -   name: Some task that fetches dependencies
          env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Build and deploy
        run: |
          mkdir dist
          cd dist

          git init

          git config --global user.name "gualter"
          git config --global user.email "gualter@gualter.com"
          

          git remote add origin git@github.com:Matyrela/Space-apps-orrery-web-app.git
          git fetch origin build || echo "No build branch yet"

          git checkout -b build || git checkout build

          cd ..

          npm install
          npm run build

          cd dist

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add *
          
          git commit -m "Deploy to build branch" || echo "No changes to commit"
          git push --force origin build
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
